 ```yaml
    name: Deploy static content to Pages

    on:
      push:
        branches: ["main"]
      workflow_dispatch:

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: true

    jobs:
      deploy:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Node
            uses: actions/setup-node@v4
            with:
              node-version: 20
          - name: Install dependencies
            run: npm install -g esbuild
          - name: Build
            run: |
              mkdir -p dist
              esbuild index.tsx --bundle --outfile=dist/index.js
              cp -r icons dist/
              cp manifest.json dist/
              cp sw.js dist/
              cp index.html dist/
              sed -i 's|<script type="module" src="/index.tsx"></script>|<script type="module" src="/index.js"></script>|' dist/index.html
              sed -i '/<script type="importmap">/,/<\/script>/d' dist/index.html
          - name: Setup Pages
            uses: actions/configure-pages@v5
          - name: Upload artifact
            uses: actions/upload-pages-artifact@v3
            with:
              path: './dist'
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
    ```
